[general]
# Note you need to clone the themes repo into ~/.config/alacritty/themes for the below to work
# Note you need to clone the themes repo into ~/.config/alacritty/themes for the below to work
import = [
    "~/.config/alacritty/themes/themes/xterm.toml"
]

[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

[font]
normal.family = "Iosevka"
size = 16.0

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
