# Set history to infinite
HISTSIZE=
HISTFILESIZE=

# add color and functionality to core-utils
# this doesn't work on macOS
alias ls='ls -hN --color=always --group-directories-first'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias sudo='sudo '

# Source aliasrc if it exists
if [ -f ~/.config/aliasrc ]; then
    source ~/.config/aliasrc
fi
