#!/bin/sh
# Machine Specific Script for Various Hosts
# To be called from xprofile

# nzxt
if [ $(uname -n) == "nzxt" ]
  then
  echo hi
fi

# tpx1
if [ $(uname -n) == "tpx1" ]
  then
  # Touchpad and Trackpoint settings
  synclient TouchpadOff=1
  synclient TapButton1=0
  synclient TapButton2=0
  synclient TapButton3=0
  synclient HorizTwoFingerScroll=1
fi

# tpx230
if [ $(uname -n) == "tpx230" ]
  then
  # Touchpad and Trackpoint settings
  echo 175 | sudo tee /sys/devices/platform/i8042/serio1/serio2/sensitivity
  echo 175 | sudo tee /sys/devices/platform/i8042/serio1/serio2/speed
  synclient TouchpadOff=1
  synclient TapButton1=0
  synclient TapButton2=0
  synclient TapButton3=0
  synclient HorizTwoFingerScroll=1
fi

# tpx201
if [ $(uname -n) == "tpx201" ]
  then
  echo hi
fi

# tpx60
if [ $(uname -n) == "tpx60" ]
  then
  echo hi
fi
