#!/bin/sh
# Machine Specific Script for Various Hosts
# To be called from xprofile

# NZXT
if [ $(uname -n) == "NZXT" ]
  then
  echo hi
fi

# TPX1
if [ $(uname -n) == "TPX1" ]
  then
  # Touchpad and Trackpoint settings
  synclient TouchpadOff=1
  synclient TapButton1=0
  synclient TapButton2=0
  synclient TapButton3=0
  synclient HorizTwoFingerScroll=1
fi

# TXP230
if [ $(uname -n) == "TPX230" ]
  then
  # Touchpad and Trackpoint settings
  echo 175 | sudo tee /sys/devices/platform/i8042/serio1/serio2/sensitivity
  echo 175 | sudo tee /sys/devices/platform/i8042/serio1/serio2/speed
  synclient TouchpadOff=1
  synclient TapButton1=0
  synclient TapButton2=0
  synclient TapButton3=0
  synclient HorizTwoFingerScroll=1
fi

# TXP201
if [ $(uname -n) == "TPX201" ]
  then
  echo hi
fi

# TXP61
if [ $(uname -n) == "TPX61" ]
  then
  echo hi
fi
