#!/usr/bin/env sh

[ -f $XDG_CONFIG_HOME/X11/Xmodmap ] && xmodmap $XDG_CONFIG_HOME/X11/Xmodmap
[ -f $XDG_CONFIG_HOME/X11/Xmachine ] && $XDG_CONFIG_HOME/X11/Xmachine
[ -f $XDG_CONFIG_HOME/X11/Xresources ] && xrdb -merge $XDG_CONFIG_HOME/X11/Xresources

# run the default screen layout
[ -f "$XDG_CONFIG_HOME/screenlayout/default.sh" ] && . $XDG_CONFIG_HOME/screenlayout/default.sh

# set screen blanking to 20 minutes
xset s 1200 &

# set screen off to 30 minutes
xset dpms 1800 1800 1800

sxhkd &
xss-lock -- i3lock -n --color=282828 &
unclutter &
picom &
dwmblocks &
dunst &
feh --no-fehbg --bg-scale ~/.local/share/wal.jpg &
dropbox &
