# add color and functionality to core-utils
alias ls='ls -hN --color=always --group-directories-first'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias sudo='sudo '

# Generate m3u Playlists
alias m3ump3='ls -1v |grep .mp3 > '
alias m3um4a='ls -1v |grep .m4a > '
alias m3uflac='ls -1v |grep .flac > '

# Set vim mode
set -o vi

# directory shortcuts
alias g8='cd /mnt/8TBRAID0'
alias gf='cd ~/docs/finances'
alias gd='cd ~/docs'
alias gD='cd ~/Dropbox'
alias gm='cd ~/mus'
alias gp='cd ~/pics'
alias gv='cd ~/vids'
alias gr='cd ~/repos'

# alias for working with config files in git bare repo
alias cfg='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias cfgp='/usr/bin/git --git-dir=$HOME/.cfgp/ --work-tree=$HOME'

# homedir cleanup
alias dosbox='dosbox -conf "$XDG_CONFIG_HOME"/dosbox/dosbox.conf'
alias tmux='tmux -f "$XDG_CONFIG_HOME"/tmux/tmux.conf'
alias abook='abook --config "$XDG_CONFIG_HOME"/abook/abookrc --datafile "$HOME"/Dropbox/apps/abook/addressbook'
alias startx='startx "$XDG_CONFIG_HOME"/X11/xinitrc'

# misc aliases
alias tvim='nvim -c "colorscheme default"'
alias trans="tremc"
alias hdc="ls -a ~ | wc -l"
alias logout='pkill -u'
alias vim='nvim'
alias w3md='w3m duckduckgo.com'
alias cls='clear'
alias taskh='task +home'
alias taskt='task +tech'
alias taskw='task +work'
alias newsboat='newsboat -c $HOME/Dropbox/apps/newsboat/cache.db'
alias yt='straw-viewer -C'
alias ytdl='youtube-dl'
alias solitaire='ttysolitaire --no-background-color'
alias newapps='sudo pacman -S --needed - < ~/repos/reprov/pacman_reprov.txt'
alias newtix='cp $HOME/docs/icanotes/tix/tix.txt $HOME/docs/icanotes/tix/"20$(date +%y)-$(date +%m)-$(date +%d).txt" && vim $HOME/docs/icanotes/tix/"20$(date +%y)-$(date +%m)-$(date +%d).txt"'

# Set history to infinite
HISTSIZE=
HISTFILESIZE=
